import random


TOPICS = [
    "Ancient Egyptian Civilization",
    "Quantum Mechanics",
    "Renaissance Art",
    "Machine Learning",
    "Climate Change",
    "World War II",
    "Nutrition and Dietetics",
    "Space Exploration",
    "Artificial Intelligence",
    "Greek Mythology",
    "Mental Health Awareness",
    "Renewable Energy",
    "Cryptocurrency",
    "Medieval Architecture",
    "Human Genome Project",
    "Sustainable Agriculture",
    "Virtual Reality",
    "The Industrial Revolution",
    "Yoga and Meditation",
    "Black Holes",
    "Blockchain Technology",
    "Impressionist Painters",
    "Global Warming",
    "Ancient Roman History",
    "Neuroscience",
    "3D Printing",
    "The Cold War",
    "Veganism",
    "Artificial Neural Networks",
    "Baroque Music",
    "Oceanography",
    "Cybersecurity",
    "The French Revolution",
    "Holistic Medicine",
    "Particle Physics",
    "Augmented Reality",
    "The Silk Road",
    "Microbiology",
    "Robotics",
    "Abstract Expressionism",
    "The Big Bang Theory",
    "Genetic Engineering",
    "The Digital Age",
    "The Mayan Civilization",
    "Immunology",
    "Internet of Things (IoT)",
    "The Harlem Renaissance",
    "Astrobiology",
    "Nanotechnology",
    "The American Civil War",
    "Mindfulness Practices",
    "Dark Matter",
    "Cloud Computing",
    "The Age of Enlightenment",
    "Traditional Chinese Medicine",
    "Astronomy",
    "Biotechnology",
    "The Viking Age",
    "Cognitive Behavioral Therapy",
    "String Theory",
    "5G Technology",
    "The Crusades",
    "Homeopathy",
    "Meteorology",
    "Autonomous Vehicles",
    "The Roaring Twenties",
    "Ayurveda",
    "Geology",
    "Smart Cities",
    "The Aztec Empire",
    "Psychotherapy",
    "Relativity Theory",
    "Wearable Technology",
    "The Great Depression",
    "Acupuncture",
    "Volcanology",
    "Edge Computing",
    "The Byzantine Empire",
    "Art Therapy",
    "The Higgs Boson",
    "Quantum Computing",
    "The Space Race",
    "Herbal Medicine",
    "Paleontology",
    "Biometrics",
    "The Protestant Reformation",
    "Music Therapy",
    "The Theory of Evolution",
    "Drone Technology",
    "The Mongol Empire",
    "Aromatherapy",
    "Marine Biology",
    "Data Science",
    "The Age of Exploration",
    "Reflexology",
    "The Solar System",
    "Cyborg Anthropology",
    "The Victorian Era",
    "Hypnotherapy",
    "Exoplanets",
    "Natural Language Processing",
    "The Inca Civilization",
    "Reiki Healing",
    "The Milky Way Galaxy",
    "Computer Vision",
    "Stranger Things (TV Show)",
    "Marvel Cinematic Universe (MCU)",
    "Elon Musk (Influencer)",
    "MrBeast (YouTuber)",
    "Climate Activism",
    "Game of Thrones (TV Show)",
    "TikTok Trends",
    "The Mandalorian (TV Show)",
    "Emma Chamberlain (YouTuber)",
    "Artificial Intelligence in Movies",
    "The Office (TV Show)",
    "Dwayne 'The Rock' Johnson (Influencer)",
    "PewDiePie (YouTuber)",
    "COVID-19 Pandemic",
    "Breaking Bad (TV Show)",
    "K-pop (Music Genre)",
    "David Dobrik (YouTuber)",
    "Black Mirror (TV Show)",
    "Greta Thunberg (Influencer)",
    "Fortnite (Video Game)",
    "Friends (TV Show)",
    "Liza Koshy (YouTuber)",
    "SpaceX (Company)",
    "The Witcher (TV Show)",
    "Casey Neistat (YouTuber)",
    "Cryptocurrency Trends",
    "The Simpsons (TV Show)",
    "Charli D'Amelio (TikTok Influencer)",
    "Tesla (Company)",
    "The Crown (TV Show)",
    "Markiplier (YouTuber)",
    "Virtual Reality Gaming",
    "Brooklyn Nine-Nine (TV Show)",
    "Addison Rae (TikTok Influencer)",
    "NASA's Artemis Program",
    "The Umbrella Academy (TV Show)",
    "Safiya Nygaard (YouTuber)",
    "E-Sports Industry",
    "The Big Bang Theory (TV Show)",
    "Zendaya (Influencer)",
    "Dream (YouTuber)",
    "Renewable Energy Innovations",
    "Westworld (TV Show)",
    "James Charles (YouTuber)",
    "Bitcoin and Blockchain",
    "The Walking Dead (TV Show)",
    "Lilly Singh (YouTuber)",
    "Deepfake Technology",
    "Grey's Anatomy (TV Show)",
    "Ryan Reynolds (Influencer)",
    "Unbox Therapy (YouTuber)",
    "Mars Colonization",
    "The Boys (TV Show)",
    "Kylie Jenner (Influencer)",
    "Linus Tech Tips (YouTuber)",
    "Artificial Meat",
    "The Flash (TV Show)",
    "Selena Gomez (Influencer)",
    "Dude Perfect (YouTuber)",
    "Quantum Computing Advances",
    "Lucifer (TV Show)",
    "Will Smith (Influencer)",
    "Good Mythical Morning (YouTuber)",
    "Augmented Reality Apps",
    "The Handmaid's Tale (TV Show)",
    "Kim Kardashian (Influencer)",
    "Philip DeFranco (YouTuber)",
    "5G Technology Rollout",
    "Money Heist (TV Show)",
    "Tom Holland (Influencer)",
    "Jenna Marbles (YouTuber)",
    "Self-Driving Cars",
    "Narcos (TV Show)",
    "Ariana Grande (Influencer)",
    "Shane Dawson (YouTuber)",
    "Smart Home Devices",
    "The Queen's Gambit (TV Show)",
    "BTS (Influencers)",
    "Jacksepticeye (YouTuber)",
    "Wearable Fitness Tech",
    "Bridgerton (TV Show)",
    "Taylor Swift (Influencer)",
    "MatPat (YouTuber)",
    "Drone Delivery Services",
    "Outer Banks (TV Show)",
    "LeBron James (Influencer)",
    "Fitness Influencers",
    "AI in Healthcare",
    "Cobra Kai (TV Show)",
    "Billie Eilish (Influencer)",
    "Beauty Gurus on YouTube",
    "Space Tourism",
    "The Falcon and the Winter Soldier (TV Show)",
    "Oprah Winfrey (Influencer)",
    "Tech Review Channels",
    "Electric Vehicles",
    "WandaVision (TV Show)",
    "Ellen DeGeneres (Influencer)",
    "True Crime Podcasts",
    "Smart Cities Development",
    "Ted Lasso (TV Show)",
    "Michelle Obama (Influencer)",
    "ASMR Content Creators",
    "Biotechnology Breakthroughs",
    "The Last of Us (TV Show)",
    "Joe Rogan (Influencer)",
    "Travel Vloggers",
    "Cybersecurity Threats"
]

def generate_random_query():
    query = random.choice(TOPICS)
    query += " #shorts"
    
    return query