name: Daily Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC (adjust timezone if needed)
  workflow_dispatch:      # Allows manual triggering


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run update_html.py
        run: python update_html.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "update $(date +'%m/%d')"
          git push